### PR TITLE
Updated external config for compass

### PR DESCRIPTION
**Pull request by weaverryan**
Hi there!

This builds off of #3 thanks to the work from @paschdan, with a few changes:

1) Removes the `add_import_path` that imported bootstrap for simplicity
2) Moves the Compass configuration file
3) Renames the variables in `Gruntfile.js` - unrelated to this really, but I think these new ones are much more descriptive.
4) Adding some more comments

@paschdan - what do you think?

Thanks!

### CODE REVIEW

**Comment by paschdan** [comment]
@weaverryan i will have a look on this in the evening stay tuned =)

**Comment by weaverryan** [comment]
cheers - thanks in advance!

**Comment by paschdan** [comment]
:+1: 
looks pretty organized, i am using a similar configuration for one of my projects, with some additions:
- i don't like the /assets/ path so my (copied) assets are lying directly under web/css 
  web/images, web/js
- i have an additional line in my compass.rb: 
  `
  generated_images_dir = "web/img" #(would be "web/assets/images" for your config)
  `
  this is because when you use the sprite-generation of compass you actually don't want the generated images in your git

**Comment by weaverryan** [comment]
Thanks for the check @paschdan! I've merged this in - it's been a really nice evolution!

**Pull request merged**
